import type { Concept, UserLevel } from "./types";

export const userLevels: UserLevel[] = [
  {
    id: "principiante",
    title: "Principiante",
    description: "Estoy empezando desde cero.",
    receives: "Recibirás explicaciones pausadas, ejemplos cotidianos y misiones pequeñas.",
  },
  {
    id: "constructor",
    title: "Constructor",
    description: "Ya he usado herramientas digitales o IA.",
    receives: "Recibirás retos más prácticos para convertir ideas en estructuras claras.",
  },
  {
    id: "arquitecto",
    title: "Arquitecto",
    description: "Ya sé programar o diseño sistemas.",
    receives: "Recibirás contexto técnico y decisiones de producto para pensar como lead builder.",
  },
];

export const appConcepts: Concept[] = [
  {
    id: "idea",
    name: "Idea",
    meaning: "Es la intención inicial de lo que quieres crear.",
    purpose: "Sirve para enfocar el problema antes de pensar en pantallas o código.",
    example: "Una app para organizar pedidos de una fonda.",
  },
  {
    id: "usuario",
    name: "Usuario",
    meaning: "Es la persona que va a usar la app.",
    purpose: "Sirve para decidir qué funciones sí importan y cuáles pueden esperar.",
    example: "La dueña de la fonda que necesita ver pedidos rápido.",
  },
  {
    id: "mvp",
    name: "MVP",
    meaning: "MVP significa Producto Mínimo Viable: una primera versión simple para probar una idea sin construir todo.",
    purpose: "Sirve para aprender rápido si la app tiene valor real.",
    example: "Primero solo catálogo, carrito y registro manual de pedidos.",
  },
  {
    id: "frontend",
    name: "Frontend",
    meaning: "Frontend significa la parte visual de una app: pantallas, botones, textos y formularios.",
    purpose: "Sirve para que el usuario pueda ver, tocar y entender la app.",
    example: "La pantalla donde eliges tacos y agregas al carrito.",
  },
  {
    id: "backend",
    name: "Backend",
    meaning: "Backend significa la parte invisible de una app: reglas, lógica, permisos y procesamiento.",
    purpose: "Sirve para que la app tome decisiones y procese información.",
    example: "Validar que un pedido tenga nombre, dirección y productos.",
  },
  {
    id: "base-datos",
    name: "Base de datos",
    meaning: "Base de datos significa el lugar donde se guarda la información.",
    purpose: "Sirve para recordar usuarios, pedidos, productos o mensajes.",
    example: "Una tabla con todos los pedidos del día.",
  },
  {
    id: "auth",
    name: "Auth",
    meaning: "Auth significa autenticación: el sistema para saber quién entra a la app.",
    purpose: "Sirve para proteger cuentas y mostrar información correcta a cada persona.",
    example: "Entrar con correo para ver solo tus pedidos.",
  },
  {
    id: "api",
    name: "API",
    meaning: "API significa una forma en que dos sistemas se comunican.",
    purpose: "Sirve para pedir o enviar datos entre partes de una app.",
    example: "El frontend pide al backend la lista de productos.",
  },
  {
    id: "storage",
    name: "Storage",
    meaning: "Storage significa almacenamiento de archivos como fotos, documentos o audios.",
    purpose: "Sirve para guardar archivos que no son solo texto.",
    example: "Fotos de los platillos del menú.",
  },
  {
    id: "roles",
    name: "Roles",
    meaning: "Roles significa permisos de cada tipo de usuario.",
    purpose: "Sirve para decidir quién puede ver, crear, editar o borrar algo.",
    example: "Cliente compra; admin cambia precios.",
  },
  {
    id: "deploy",
    name: "Deploy",
    meaning: "Deploy significa publicar la app para que otras personas puedan usarla.",
    purpose: "Sirve para pasar de tu computadora a una dirección web real.",
    example: "Subir la app para compartirla con clientes.",
  },
  {
    id: "logs",
    name: "Logs",
    meaning: "Logs significa registros de lo que pasa dentro de la app.",
    purpose: "Sirve para encontrar errores y entender el comportamiento del sistema.",
    example: "Ver que un pedido falló porque faltó el teléfono.",
  },
  {
    id: "tests",
    name: "Tests",
    meaning: "Tests significa pruebas para verificar que algo funciona.",
    purpose: "Sirve para reducir errores cuando haces cambios.",
    example: "Probar que el carrito suma bien el total.",
  },
  {
    id: "git",
    name: "Git",
    meaning: "Git significa herramienta para guardar el historial de cambios del código.",
    purpose: "Sirve para regresar a versiones anteriores y colaborar con orden.",
    example: "Guardar un cambio con un commit antes de seguir editando.",
  },
  {
    id: "localstorage",
    name: "localStorage",
    meaning: "localStorage es una memoria pequeña del navegador para guardar datos en tu computadora.",
    purpose: "Sirve para conservar progreso local sin usar servidor.",
    example: "Guardar tus puntos aunque cierres la pestaña.",
  },
  {
    id: "pantalla",
    name: "Pantalla",
    meaning: "Pantalla significa una vista de la app que la persona puede ver y usar.",
    purpose: "Sirve para organizar una tarea específica, como capturar datos o revisar una lista.",
    example: "La pantalla principal de una lista de pendientes.",
  },
  {
    id: "componente",
    name: "Componente",
    meaning: "Componente significa una pieza reutilizable de una interfaz, como un botón, tarjeta o formulario.",
    purpose: "Sirve para construir pantallas con partes ordenadas que puedes repetir.",
    example: "Una tarjeta que muestra un cliente y se puede usar muchas veces.",
  },
  {
    id: "estado",
    name: "Estado",
    meaning: "Estado significa información que cambia mientras usas una app.",
    purpose: "Sirve para que la interfaz recuerde lo que elegiste, escribiste o guardaste.",
    example: "El texto que aparece mientras escribes el nombre de un cliente.",
  },
  {
    id: "formulario",
    name: "Formulario",
    meaning: "Formulario significa un bloque donde el usuario escribe información.",
    purpose: "Sirve para capturar datos de forma ordenada antes de guardarlos.",
    example: "Campos para nombre, teléfono y nota.",
  },
  {
    id: "campo",
    name: "Campo",
    meaning: "Campo significa un espacio donde el usuario puede escribir un dato.",
    purpose: "Sirve para separar cada pieza de información que quieres guardar.",
    example: "Un campo llamado teléfono dentro de un formulario de clientes.",
  },
  {
    id: "registro",
    name: "Registro",
    meaning: "Registro significa un dato guardado, por ejemplo un cliente, una tarea o un pedido.",
    purpose: "Sirve para convertir lo que escribió el usuario en información que la app puede mostrar después.",
    example: "Un cliente guardado con nombre, teléfono y nota.",
  },
  {
    id: "guardado-local",
    name: "Guardado local",
    meaning: "Guardado local significa guardar datos en el navegador o computadora sin usar servidores externos.",
    purpose: "Sirve para que la app conserve información aunque cierres la pestaña.",
    example: "Guardar tus registros de prueba en localStorage.",
  },
  {
    id: "vista-previa",
    name: "Vista previa",
    meaning: "Vista previa significa una representación visual de cómo se vería algo antes de publicarlo.",
    purpose: "Sirve para revisar una pantalla o formulario antes de construir una versión real.",
    example: "Ver cómo se verá el botón principal de tu app local.",
  },
  {
    id: "typescript",
    name: "TypeScript",
    meaning: "TypeScript es JavaScript con tipos claros para describir mejor los datos.",
    purpose: "Sirve para detectar errores antes de correr la app.",
    example: "Indicar que los puntos siempre deben ser un número.",
  },
];

export const getConcept = (id: string) => appConcepts.find((concept) => concept.id === id);
